repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v3.4.0
  #   hooks:
  #   -   id: trailing-whitespace
  #       files: ^backend/
  #   -   id: end-of-file-fixer
  #       files: ^backend/
  #   -   id: check-yaml
  #       files: ^backend/
  #   -   id: check-added-large-files
  #       files: ^backend/
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
  - repo: https://github.com/biomejs/pre-commit
    rev: v0.1.0
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.4.1"]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        args: [--line-length=100]
        files: ^backend/

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
    -   id: isort
        files: ^backend/

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        files: ^backend/

ci:
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
  autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
