version: "3.7"
services:
  proxy:
    image: traefik:v2.9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./lb.yml:/config.yml:ro
    ports:
      - 7000:7000
      - "7001:8080"
    # Duplicate the command from docker-compose.yml to add --api.insecure=true
    command:
      - traefik
      - --entrypoints.dev.address=:7000
      - --providers.file.filename=/config.yml
      - --api.insecure=true
      
  db:
    image: postgres:12
    restart: always
    networks:
      - traefik-public
      - default
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}

  adminer:
    image: adminer
    restart: always
    networks:
      - traefik-public
      - default
    depends_on:
      - db
    environment:
      - ADMINER_DESIGN=pepa-linha-dark

  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    restart: always
    networks:
      - traefik-public
      - default
    depends_on:
      - db
    env_file:
      - .env

    build:
      context: ./backend
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    platform: linux/amd64 # Patch for M1 Mac
    command: /start-reload.sh
    volumes:
      - ./backend/:/app


  frontend:
    image: '${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}'
    restart: always
    networks:
      - traefik-public
      - default
    depends_on:
      - backend
    build:
      context: ./frontend
      args:
        - NODE_ENV=production
    command: npm run dev
    volumes:
      - ./frontend:/app
      # - ./frontend/node_modules:/app/node_modules
      - /app/node_modules
    env_file:
      - .env
volumes:
  app-db-data:

networks:
  traefik-public:
    # Allow setting it to false for testing
    external: false
