version: "3.8"
services:

  db:
    image: postgres:12
    container_name: db
    env_file:
      - .env
    ports:
      - "4003:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 4005:8080
    depends_on:
      - db

volumes:
  postgres_data:
