services:
  traefik:
    image: traefik:2.10.3
    command:
      - traefik
      - --entryPoints.dev.address=:4000
      - --providers.file.filename=/config.yml
    ports:
      - 4000:4000
    volumes:
      - ./lb-local.yml:/config.yml:ro

  api:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    build:
      context: ../backend
    env_file:
      - ${ENV_FILE:-local.env}
    ports:
      - 4002:4002
    volumes:
      - ../backend:/app/

  frontend:
    image: '${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}'
    build:
      context: ../frontend
    env_file:
      - ${ENV_FILE:-local.env}
    ports:
      - 4001:4001
    volumes:
      - ../frontend:/app

  ddb:
    image: postgres:12
    env_file:
      - ${ENV_FILE:-local.env}
    ports:
      - 4003:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adm:
    image: adminer
    ports:
      - 4004:8080
    depends_on:
      - ddb

volumes:
  postgres_data:
